name: Sysdig Image Scan

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      
      - name: Pull sample image
        run: docker pull nginx:latest

      - name: Sysdig Image Scan
        uses: sysdiglabs/scan-action@v4
        with:
          sysdig_secure_url: "https://app.au1.sysdig.com"   # or in1 / au1 etc
          sysdig_secure_api_token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          image_tag: "myapp:latest"        # Image to scan
          fail_on_critical: true           # Optional – break build on findings
          policy: "Default"                # Optional – enforce specific policy

      - name: Upload Sysdig Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-report
          path: scan_results.json
