name: Sysdig Image Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y podman buildah
          curl -fsSL https://get.docker.com | sudo sh
          sudo usermod -aG docker $USER

      - name: Pull sample image
        run: docker pull nginx:latest

      - name: Sysdig Image Scan
        uses: sysdiglabs/scan-action@v4
        with:
          sysdig-secure-url: "https://app.au1.sysdig.com"
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          image-tag: "nginx:latest"
          override-pullstring: "docker-daemon:myapp:latest"
          stop-on-failed-policy-eval: true
          use-policies: "Default"

      - name: Upload Sysdig Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: sysdig-report
          path: scan_results.json
